version: 0.2

phases:

  install:
    commands:
      - apt-get install python3.7 -y
      - python3 --version
      - pip install awsebcli --upgrade --user
      - export PATH=~/.local/bin:$PATH
      - source ~/.bashrc
      - eb --version
  # pre_build:
    # commands:
      # - terraform init

  # build:
    # commands:
      # - terraform destroy -var-file=demo.json -auto-approve

  # post_build:
   # commands:
      # - echo terraform apply completed on `date`