version: 0.2

env:
  secrets-manager:
    url: "$appname:url"
    dbname: "$appname:dbname"
    name: "$appname:username"
    pass: "$appname:password"
    port: "$appname:port"


phases:

  build:
    commands:
      - ls
      - aws elasticbeanstalk update-environment --environment-name $appname --option-settings file://options.json
      - cd ./wordpress-beanstalk
      - zip ../wordpress-beanstalk.zip -r * .[^.]*
      - cd ..
      - ls
artifacts:
  files:
    - ./wordpress-beanstalk.zip