version: 0.2

env:
  secrets-manager:
    url: "$appname:url"
    dbname: "$appname:dbname"
    name: "$appname:username"
    pass: "$appname:password"
    port: "$appname:port"


phases:

  build:
    commands:
      - ls
      - cd ./wordpress-beanstalk/.ebextensions
      - 'echo "    RDS_HOSTNAME: $url" >> wordpress.config'
      - 'echo "    RDS_DB_NAME: $dbname" >> wordpress.config'
      - 'echo "    RDS_USERNAME: $name" >> wordpress.config'
      - 'echo "    RDS_PASSWORD: $pass" >> wordpress.config'
      - 'echo "    RDS_PORT: $port" >> wordpress.config'
      - cat wordpress.config
artifacts:
  files:
    - ./wordpress-beanstalk/**/*
    - ./wordpress-beanstalk/.ebextensions/**/*
    - ./wordpress-beanstalk/wp-admin/**/*
    - ./wordpress-beanstalk/wp-content/**/*
    - ./wordpress-beanstalk/wp-includes/**/*