version: 0.2

env:
  secrets-manager:
    url: "$appname:url"
    dbname: "$appname:dbname"
    name: "$appname:username"
    pass: "$appname:password"
    port: "$appname:port"


phases:

  install:
    commands:
      - cd /wordpress-beanstalk/.ebextensions
      - 'echo "    RDS_HOSTNAME: $url" >> wordpress.config'
      - 'echo "    RDS_DB_NAME: $dbname" >> wordpress.config'
      - 'echo "    RDS_USERNAME: $name" >> wordpress.config'
      - 'echo "    RDS_PASSWORD: $pass" >> wordpress.config'
      - 'echo "    RDS_PORT: $port" >> wordpress.config'
      - cat wordpress.config
  # pre_build:
    # commands:
      # - terraform init

  # build:
    # commands:
      # - terraform destroy -var-file=demo.json -auto-approve

  # post_build:
   # commands:
      # - echo terraform apply completed on `date`