version: 0.2

env:
  secrets-manager:
    url: "$appname:url"
    dbname: "$appname:dbname"
    name: "$appname:username"
    pass: "$appname:password"
    port: "$appname:port"
    vpcid: "$appname:vpcid"
    subnet1: "$appname:prisuba"
    subnet2: "$appname:prisubb"
    rdssg: "$appname:rdssg"
    cfid: "$appname:cfid"


phases:
 build:
    commands:
      - echo compiling package

artifacts:
  files:
    - '**/*'
  base-directory: 'webapp'
  name: webapp