version: 0.2

env:
  secrets-manager:
    url: "$appname:url"
    dbname: "$appname:dbname"
    name: "$appname:username"
    pass: "$appname:password"
    port: "$appname:port"


phases:
  pre_build:
    commands:
      - vpcid=$(aws rds describe-db-instances --db-instance-identifier $appname | python -c "import sys, json; print(json.load(sys.stdin)['DBInstances'][0]['DBSubnetGroup']['VpcId'])")
      - subnet1=$(aws rds describe-db-instances --db-instance-identifier $appname | python -c "import sys, json; print(json.load(sys.stdin)['DBInstances'][0]['DBSubnetGroup']['Subnets'][0]['SubnetIdentifier'])")
      - subnet2=$(aws rds describe-db-instances --db-instance-identifier $appname | python -c "import sys, json; print(json.load(sys.stdin)['DBInstances'][0]['DBSubnetGroup']['Subnets'][1]['SubnetIdentifier'])")
      - subnet3=$(aws rds describe-db-instances --db-instance-identifier $appname | python -c "import sys, json; print(json.load(sys.stdin)['DBInstances'][0]['DBSubnetGroup']['Subnets'][2]['SubnetIdentifier'])")
  build:
    commands:
      - ls
      - cd ./wordpress-beanstalk/.ebextensions
      - aws elasticbeanstalk update-environment --environment-name $appname --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_HOSTNAME,Value=$url
      - sleep 45
      - aws elasticbeanstalk update-environment --environment-name $appname --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_DB_NAME,Value=$dbname
      - sleep 45
      - aws elasticbeanstalk update-environment --environment-name $appname --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_USERNAME,Value=$name
      - sleep 45
      - aws elasticbeanstalk update-environment --environment-name $appname --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_PASSWORD,Value=$pass
      - sleep 45
      - aws elasticbeanstalk update-environment --environment-name $appname --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_PORT,Value=$port
      - sleep 45
      # - 'echo "    RDS_HOSTNAME: $url" >> wordpress.config'
      # - 'echo "    RDS_DB_NAME: $dbname" >> wordpress.config'
      # - 'echo "    RDS_USERNAME: $name" >> wordpress.config'
      # - 'echo "    RDS_PASSWORD: $pass" >> wordpress.config'
      # - 'echo "    RDS_PORT: $port" >> wordpress.config'
      - cat wordpress.config
      - sed "s/vpc-XXXXX/$vpcid/g" efs-create.config.template > efs-create.config.template1
      - sed "s/subnet-XXXXX1/$subnet1/g" efs-create.config.template1 > efs-create.config.template2
      - sed "s/subnet-XXXXX2/$subnet2/g" efs-create.config.template2 > efs-create.config.template3
      - sed "s/subnet-XXXXX3/$subnet3/g" efs-create.config.template3 > efs-create.config
      - cat efs-create.config
      - rm efs-create.config.template
      - rm efs-create.config.template1
      - rm efs-create.config.template2
      - rm efs-create.config.template3
artifacts:
  files:
    - '**/*'
  base-directory: 'wordpress-beanstalk'
  name: wordpress-beanstalk