version: 0.2

env:
  secrets-manager:
    url: "$appname:url"
    dbname: "$appname:dbname"
    name: "$appname:username"
    pass: "$appname:password"
    port: "$appname:port"


phases:

  build:
    commands:
      - ls
      - cd ./wordpress-beanstalk
      - aws elasticbeanstalk update-environment --environment-name $appname --option-settings [{Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_HOSTNAME,Value=$url},{Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_DB_NAME,Value=$dbname},{Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_USERNAME,Value=$name},{Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_PORT,Value=$port},{Namespace=aws:elasticbeanstalk:application:environment,OptionName=RDS_PASSWORD,Value=$pass}]
      - zip ../wordpress-beanstalk.zip -r * .[^.]*
      - cd ..
      - ls
artifacts:
  files:
    - ./wordpress-beanstalk.zip